### ISSUE TITLE
Move BitField and type_casts into utils

### ISSUE THREAD

**Issue by mundya** [project-rig/rig#106]
Migrate `bitfield.py` and `type_casts.py` into `utils`: I think this would lead to a clearer split in functionality.

**Comment by mundya** [comment]
`geometry.py` should also move.

**Comment by mossblaser** [comment]
Agreed. That said, the top-level "utils" is currently more of the "internal utils" flavour. Not sure what to do on that front...

**Comment by mundya** [comment]
`internal_utils`... shudder...  Nengo has the same problem, internal and external utils are stored in one directory.  I think we'd probably be fine to maintain this for now.

**Comment by mossblaser** [comment]
Perhaps the above utils could get a module better name? They're no more a "util" than place and route, after all?

**Comment by mossblaser** [comment]
Closed for now pending "seeing what happens."

**Comment by mundya** [comment]
Yay API flux.
