### ISSUE TITLE
Add Overview-Level Documentation

### ISSUE THREAD

**Issue by mossblaser** [project-rig/rig#110]
Rig's docs are currently lacking in answering the question "where do I start and what do I still need to do myself?". Additionally, the README is suffering some wear and tear.

* Rewrite high-level introductory text
  * [x] README
  * [x] Documentation index page
  * [x] PyPi Page
* [x] Attempt to distinguish auto-generated API reference from other documentation
* [x] API Overview -- mostly just enumerate top-level submodules
* [x] Point documentation links at "stable" RTD link.
* [x] Document CLI utility applications (e.g. rig-boot and friends)
* [x] Split developer-relevant README.md material into `DEVELOP.md`
* [x] Document distribution process
* Document unique testbench features
  * [x] Document the test ordering feature
  * [x] Document how to enable doctest in sphinx docs (i.e. set the filename)
  * [x] Outline how the live testing works
* [x] Some suitably tiny example (<50 lines) which may not do much but should show off the PAR -> machine flow -- bonus points for being small enough to include in the README.

**Comment by mundya** [comment]
A [perhaps ridiculous] example, but how about some gate-level simulation?  That way the place and route get to do something trivial but relatively easy to express?

**Comment by mossblaser** [comment]
Null convention logic?

That sounds like a jolly good idea anyway! I'd skip the carry look-ahead for simplicity's sake ;)

**Comment by mundya** [comment]
> Null convention logic?

10.1109/ASAP.1996.542821

To be fair, a 4 bit adder would be just as illustrative.  Spot the microelectronics engineer.

**Comment by mossblaser** [comment]
Tutorials and a simple README example have finally been added. Closing this issue!
