### ISSUE TITLE
Boot improvements

### ISSUE THREAD

**Issue by mundya** [project-rig/rig#118]
Booting should probably wait until the board responds to pings before actually attempting to boot.

**Comment by mossblaser** [comment]
Not sure I understand this one? Are you suggesting making the "boot" command in MachineController check the machine is alive after booting or something completely different?

**Comment by mundya** [comment]
More that before sending any boot packets (https://github.com/project-rig/rig/blob/master/rig/machine_control/boot.py#L154 onwards) the target address should be pinged to ensure that the board has fully powered on.  It's not a huge issue but I occasionally manage to try booting a board after just resetting it.

**Comment by mundya** [comment]
Although it sounds like this may be a faff... hmm...

**Comment by mundya** [comment]
"As it uses raw ICMP sockets, you need to be root to use the functions exported by the ping module." - https://pypi.python.org/pypi/ping/0.2
