### ISSUE TITLE
(Optional) Buffered writing via file-IO.

### ISSUE THREAD

**Issue by mossblaser** [project-rig/rig#124]
In my network_tester application, and potentially others, a convenient mode of operation is to pass (slices of) MemoryIO objects around to different parts of the program which may then make small writes to memory which may be to sequential regions. As such, for efficiency it would be beneficial to combine these small sequential writes into a single continuous write. This means that maximum-sized writes, and thus maximum network efficiency can be achieved and also that future introduction of #117 (Windowed reads/writes) could be made even more widely applicable.

I propose the following:

* Add a `write_buffer_size` property which defaults to 0 (meaning maintain current behaviour) but can be set to an arbitrary number of bytes (up to the size of the slice).
* When calling `write(...)`, if the write would be contiguous with previously buffered data and the data will fit in the allocated write-buffer, the data is silently buffered and not sent. Otherwise, the data is sent immediately.
* Add `flush()` method which sends any data currently in the write buffer.
* Slices of the same original MemoryIO share the same write buffer: this allows writes within slices to be merged too.

Note that:

* Only buffering contiguous writes is an intentional simplification of the problem since otherwise you have to deal with re-ordering buffered writes etc. Since the same API would be presented by a more sophisticated system, this mechanism could be implemented at a later point without breaking backward compatibility.
* Sadly, unlike normal OS buffered writes, nothing happens until you hit `flush()`. As such if you use buffered writes, you *must* hit flush at some point. Still, I think this is still useful since it allows coalescing of writes with minimal code in the user application.

@mundya @neworderofjamie Any thoughts as implementers of related systems?

**Comment by mundya** [comment]
+1

**Comment by neworderofjamie** [comment]
This sounds a fine idea to me - I might be getting the wrong end of the
stick here, but perhaps flushing could be automated so it always flushes
when you perform a non-coalesced write and always when you 'close' your
memory handle in some way.

**Comment by mundya** [comment]
> flushing could be automated so it always flushes when you perform a non-coalesced write

This, and perhaps whenever you perform a read.

Sadly, detecting object deletion in Python is not reliable:

> so `__del__` can't serve as a replacement for good coding practices (like always closing a connection when you're done with it. **In fact, `__del__` should almost never be used because of the precarious circumstances under which it is called; use it with caution!**

http://www.rafekettler.com/magicmethods.html

But we could do the standard Python `with` syntax for flushing.

```python
with file_like:
    file_like.write(...)
# file_like flushed on leaving the `with`
```

**Comment by mossblaser** [comment]
> > so `__del__` can't serve as a replacement for good coding practices (like always closing a connection when you're done with it. 

![XKCD](https://imgs.xkcd.com/comics/\(.png)

**Comment by mundya** [comment]
I hasten to add the the umatched parenthesis isn't mine.
