### ISSUE TITLE
sdram_alloc_for_vertices missing buffer_size argument

### ISSUE THREAD

**Issue by mundya** [project-rig/rig#133]
#125 introduced the `buffer_size` argument for `sdram_alloc_as_filelike`.  This argument should be exposed in `utils.sdram_alloc_for_vertices`.

**Comment by mossblaser** [comment]
Whoops! Sorry I missed that one!

**Comment by mundya** [comment]
> Sorry I missed that one!

We both missed that...  Probably means the API is getting a little big.
