### ISSUE TITLE
Version number in documentation is wrong

### ISSUE THREAD

**Issue by mossblaser** [project-rig/rig#139]
This isn't kept in sync automatically... Joy!

**Comment by mundya** [comment]
Do we want to go for `__version__` somewhere?

**Comment by mossblaser** [comment]
I think so! I've made a "version.py" which defines `__version__` and is imported in the relevent places, setup.py just execs that file directly and the docs import `spinner.__version__`. Seems to work nicely enough!

https://github.com/SpiNNakerManchester/SpiNNer/commit/55542138e02422f5add9f42c24554c5591ac42aa

**Comment by mundya** [comment]
Cool, thank you :)
