### ISSUE TITLE
Clearing routing table entries

### ISSUE THREAD

**Issue by mundya** [project-rig/rig#149]
It occurs to me that the simulated annealing placement, and just bigger boards and models, makes it much more important that routing table entries are definitely cleared. Pending SpiNNaker tools 1.4 should we add a method to achieve this?

**Comment by mossblaser** [comment]
This is true... Not sure where exactly it should live, mind...

**Comment by mossblaser** [comment]
(This, strictly speaking, was a problem even with hilbert placement too, of course).

**Comment by mundya** [comment]
Is there any chance we could ask Steve to make this as a minor change to the existing tools?

**Comment by mossblaser** [comment]
Probably not given his current schedule and the relatively small subset of people who care about it in the short term. :(.

I'd probably stick in a very angrily commented thing on the send-signal command which simply "does the business" on app stop. :/

All a bit 'orrible :(.

**Comment by mundya** [comment]
> Probably not given his current schedule and the relatively small subset of people who care about it in the short term. :(.

Will someone think of the Spaun?
