### ISSUE TITLE
Add a "share resources" constraint

### ISSUE THREAD

**Issue by mossblaser** [project-rig/rig#184]
This placement and allocation constraint would allow constrained vertices to be allocated the same resource ranges when placed on the same chip (but otherwise behave normally).

Example Usage
-------------------

This (for instance) allows placement of applications in which all application cores require access to a copy of a certain block of memory. In this instance, there is no need to allocate multiple copies of the memory block per chip but there must always be (at least) one copy of the block on any chip on which an associated application core is placed.

As an example, say we have two vertices `v0` and `v1`, which represent our two application cores. We can associate each with a vertex, `m0` and `m1` respectively which represents the copy of the memory block used by the vertices.

```
vertices_resources = {
    v0: {Cores: 1},
    m0: {SDRAM: 1024},
    v1: {Cores: 1},
    m1: {SDRAM: 1024},
}
```

We then use a `SameChipConstraint` to ensure the memory blocks each get placed on the same chip as the application cores:

```
constraints.append(SameChipConstraint([v0, m0]))
constraints.append(SameChipConstraint([v1, m1]))
```

Finally, we can use the proposed `ShareResourcesConstraint` to indicate that the two memory blocks can be allocated the same resources if they're placed on the same chip.

```
constraints.append(ShareResourcesConstraint([m0, m1]))
```

A similar arrangement of constraints and core-less vertices may also be used (for example) to allow IP Tags to be allocated shared.

Implementation details
----------------------------

This constraint will sadly require a bit of a faff on the part of all involved placement algorithms which I can't see an easy way to avoid. As such it will affect the calculation used to determine the resources consumed by placing a vertex on a given chip. This calculation is further complicated by the effects of `SameChipConstraints` which at present are implemented by merging together vertices. Most likely, each vertex will need some additional value associated with it which gives the resources which can be shared with any of the neighbouring vertices... Ugh...

**Comment by mundya** [comment]
It may also require some changes to `sdram_alloc_for_vertices` if we want to ensure a smooth flow through the toolchain...

**Comment by mossblaser** [comment]
I'm going to close this since there is no appetite for the horror that might be implementing this and I'm doubtful that this would be the correct way (long term) to solve the problem of running out of IPtags on a monitor processor... (i.e. SC&MP should be altered to increase the number of available tags until this isn't a problem...)
