### ISSUE TITLE
Consider removal of write buffering in MachineController

### ISSUE THREAD

**Issue by mossblaser** [project-rig/rig#190]
Something to consider before the 1.0 release since this would be breaking change.

This feature is not used by anyone and upon further thought doesn't help much since producing lots of small writes suggests your application is poorly optimising the way it generates data to send to the machine This feature is also full of fun edge-cases and potential subtle bugs in application using it so must have a clearly defined use-case to legitimise its continued existence.

**Comment by mundya** [comment]
Were you using this @neworderofjamie?

**Comment by mundya** [comment]
This was removed by #229.
