### ISSUE TITLE
Load routing table entries like loading applications

### ISSUE THREAD

**Issue by mundya** [project-rig/rig#47]
We have `load_applications` which accepts the `application_map` created by place and route but we don't have an analogue for routing tables.

Propose adding `load_routing_tables` which is just a thin wrapper around `load_routing_table_entries` but accepts the output of the place and route tools as input.

**Comment by mossblaser** [comment]
Presumably this wrapper is just a for-loop over the dictionary from PAR? Sounds reasonable to me! Do it!
