### ISSUE TITLE
Future Improved IO Plans/Thoughts

### ISSUE THREAD

**Issue by mossblaser** [project-rig/rig#63]
* Blocking interfaces should always be present and should continue to work just like they do now
* Plenty of performance is lost to waiting for roundtrips on SCP commands
  * Must ask ST what restrictions apply to current implementations/his thoughts on having multiple open SCP requests
  * In many cases, blocking functions make lots of potentially-parallel SCP calls (e.g. get_machine), thus many functions with blocking interfaces would end up being faster for free.
* In the future, opportunities will exist for using multiple endpoints simultaneously for SCP
  * Should ask ST about side-effects of communicating with the system from multiple ethernet (or otherwise) links. I would guess none.
  * It might not be necessary/beneficial to limit comms to just use of the local ethernet connection
* Alternative interface should allow the queuing/dispatching of many SCP commands at once
  * Should, behind the scenes, schedule these commands appropriately (i.e. limit maximum outstanding commands)
  * Some plan needs to be implemented to handle deferred responses
    * Callbacks on completion (messy)
    * ~~Use a "real" framework for this (e.g. Twisted)~~
    * Methods could be "two-phase" generators
      * Calling the method yields after the command is either queued or sent
      * Doing a next() on the generator would then produce the received response, blocking until the command has both been sent and the response received. The generator could then yield the response or throw an appropriate exception (e.g. timeout)
      * Potentially, enabling this mode could simply be an argument of all the existing commands -- better still, it would make it possible to use a decorator for this function. Also, as an argument it can be set by the context -- schweet.
      * Additionally provide some flush-style function which blocks until all commands have been sent and responded to.
      * Clearly JH has taken a liking to this idea

**Comment by mundya** [comment]
> - Use a "real" framework for this (e.g. Twisted)

Twisted would require rethinking most of the API, for the record I'm against using it.

**Comment by mossblaser** [comment]
Just had a chat with ST:
* There is a hard-limit on the number of outstanding connections going through a ethernet-connected monitor imposed by the transient IPTag pool size (a transient IP tag is created for every SCP cmd). This can be queried from the machine. This can also be cheaply extended if it proves valuable.
* If the bandwidth/latency ratio for loading a core is sufficiently good (unverified but highly plausible) then the only situations where parallel requests are useful is when many cores are being loaded/polled simultaneously.
* Having multiple outstanding SCP requests where each request is to a different core doesn't require any new flow-control mechanisms in SCP.
* ST recommends only using the ethernet connection local to a given chip for comms.

May not be too bad!

**Comment by mossblaser** [comment]
So first off, here's a sketch of how implementing/using the non-blocking stuff could look:

```
class MachineController(object):

    ...

    def my_non_blocking_thing():
        # Queues/sends the command
        token = self.send_scp(...)
        yield
        
        # Either returns the already-recieved response or blocks until response
        # has been received. This function contains a mainloop which
        # sends/receives queued commands.
        packet = self.wait_for_response(token)
        yield packet.data

# Make a load of requests
outstanding_requests = []
for _ in range(10):
    gen = mc.my_non_blocking_thing()
    next(gen)  # Triggers the sending of the command
    outstanding_requests.append(gen)

# Now make use of the replies
for gen in outstanding_requests:
    print(next(gen))
```

Of course, blocking interfaces are easy and actually are all people want half the time. By adding a simple decorator to the above API you can make it look blocking. Even better, that decorator can make the async-version accessible via an option:

```
def look_blocking(f):
    """Decorator."""
    def f_(*args, **kwargs, async=False):
        g = f(*args, **kwargs)
        if async:
            return g
        else:
            next(g)
            return next(g)
    return f_

class MachineController(object):

    ...

    @look_blocking
    def my_non_blocking_thing():
        token = self.send_scp(...)
        yield
        packet = self.wait_for_response(token)
        yield packet.data

# Blocking mode (default)
print(mc.my_non_blocking_thing(...))

# Non-blocking mode
gen = mc.my_non_blocking_thing(..., async=True)
next(gen)
response = next(gen)
```

/me is really quite excited by this interface and based on the excuse that "the test suite/get_machine is zlow over the web" that's enough motivation for me to start working on this...

**Comment by mundya** [comment]
I'm interested to see how this turns out.

**Comment by mossblaser** [comment]
A pseudo-code-dump of approximately my planned implementation. Feedback welcome but more for my own archival use than anything else :)

```
class SCPConnection(object):

    def queue_scp_packet(self, x, y, p, ...):
        t = self.get_token()
        p = SCPPacket(...)
        self.queue[(x, y, p)].append((t, p))
        self.dispatch_if_possible()
        return t
    
    
    def process_incoming_packet(self):
        # Check if any packets are available (operate in non-blocking mode)
        data = self.sock.recv(self.recv_size)
        
        # Handle arrived packets
        for resends, send_time, token, packet in self.outstanding:
            if data is not None and packet.seq = data.seq:
                del self.outstanding[packet]
                del self.outstanding_cores[packet.xyp]
                self.responses[token] = data
    
    def timeout_tick(self):
        for resends, send_time, token, packet in self.outstanding:
            if now() - send_time > self.timeout:
                if resends > self.max_tries:
                    del self.outstanding[packet]
                    del self.outstanding_cores[packet.xyp]
                    self.responses[token] = TimeoutError()
                else:
                    sock.send(p)
                    resends += 1
                    send_time = now()
    
    def dispatch_if_possible(self):
        # Dispatch queued packets if capacity available and there are packets
        # queued for cores not currently being sent-to
        while (len(self.outstanding) < self.max_outstanding and
               self.queue.difference(outstanding_cores)):
            token, packet = self.queue.get_next(outstanding_cores)
            packet.seq = self.new_seq_num()
            self.sock.send(p)
            self.outstanding.append((resends=0, send_time=now(), token=token, packet=packet))
            self.outstanding_cores.add((x, y, p))
    
    def wait_for_response(self, token=None):
        # Wait until the response for the given token arrives (or it times
        # out). Alternatively if token is None, wait until all outstanding
        # packets are processed.
        while ((token is not None and token not in self.responses) or
               (token is None and self.outstanding)):
            # Wait until a packet arrives or one may have timed out
            arrived, _1, _2 = select([self], [], [], timeout=self.next_timeout())
            if arrived:
                self.process_incoming_packet()
            self.timeout_tick()
            self.dispatch_if_possible()
        if token is not None:
            response = self.responses.pop(token)
            if isinstance(response, Exception):
                raise response
            else:
                return response



class MachineController(object):

    def queue_scp_packet(self, x, y, p, ...):
        scp_conn = get_nearest_connection(x, y, p)
        t = scp_conn.queue_scp_packet(x, y, p, ...)
        self.token_to_connection[t] = scp_conn
        return t
    
    def wait_for_response(self, token=None):
        while ((token is not None and token not in self.token_to_connection[token].responses) or
               (token is None and any(c.outstanding for c in self.connections))):
            # Wait for a timeout or data to arrive
            to_read, _1, _2 = select(self.connections, [], [], timeout=self.next_timeout())
            
            # Process arriving data
            for conn in to_read:
                conn.process_incoming_packet()
            
            # Process timeouts and sending new data if possible
            for conn in self.connections:
                conn.timeout_tick()
                conn.dispatch_if_possible()
        if token is not None:
            response = self.token_to_connection[token].responses.pop(token)
            if isinstance(response, Exception):
                raise response
            else:
                return response
```

**Comment by mossblaser** [comment]
Further chatting with ST:

* Existing SCAMP/SARK may have slight issues with being sent n_transient_iptags*full_size_scp packets at once: new coming-soon SCAMP/SARK have *much* more buffering and won't blink at this.
* The transient tags have a timeout after while they are re-cycled if no SCP reply comes back (e.g. due to network congestion/code deadness).
  * Since retransmitting a packet requires a new transient tag, retransmit timeouts *must* be long enough to allow this timeout to expire to free up the transient tag (if out of transient tags, the machine just silently drops the SCP packet).
  * Current default transient tag time is 2-or-so seconds. According to ST, this should be very safe to change to 10ms since no SCP command should ever take that long to run and the network should never be that slow, even accounting for network delays within SpiNNaker
  * Transient tag timeouts can be read/set using the IPTAG_TTO command. Timeouts are encoded as `10ms * (1 << (v - 1))`. This command also gives the number of transient tags.

**Comment by mossblaser** [comment]
Regrettably I'm mothballing this implementation on account of its lacklustre performance. Follow #77 for its successor!
