### ISSUE TITLE
Routing entries not removed when app is stopped

### ISSUE THREAD

**Issue by mossblaser** [project-rig/rig#67]

**Comment by mundya** [comment]
This seems to be because there are two different app stop mechanisms, in ybug:
`app_stop app_id` != `app_sig all app_id stop`

The former removes routing table entries, the latter doesn't.  I'll check this with ST tomorrow.

**Comment by mundya** [comment]
Ug, not that simple.

**Comment by mundya** [comment]
On checking with ST: currently routing table entries on chips without an application with the same ID will not be removed when `app_stop` is sent.  Consequently this is out of my hands.  ST has noted this as a feature request for implementation at some later point.
