### ISSUE TITLE
Proposal: Drop Python 3.3 support

### ISSUE THREAD

**Issue by mossblaser** [project-rig/rig#76]
* Who ships python 3.3 which should be considered an important target?
* Would cut 33% of unit test runtime
* Make is far easier to reproduce tests on modern linux distributions using tox (python 3.3 isn't easy to get)

**Comment by mundya** [comment]
> - Who ships python 3.3 which should be considered an important target?

The version of Fedora on my work machine... :cry: 

In principle I agree, supporting the most recent version of 3 and 2.7 should probably be sufficient.

**Comment by mundya** [comment]
Is "cutting test time" a good reason to drop support for something?

**Comment by mossblaser** [comment]
Lol, not really, though it is the most obvious source of developer resource drain that supporting unnecessary platforms produces...

**Comment by mossblaser** [comment]
My goodness  was it only 8 days...

Anyway, this is being reopened and will be applied after #119 #121 have been merged in.

**Comment by mundya** [comment]
> My goodness was it only 8 days...
March != April... sorry

**Comment by mossblaser** [comment]
> mossblaser closed this 8 days ago

**Comment by mundya** [comment]
|| mossblaser closed this 8 days ago

Fair enough. Time flies.
