### ISSUE TITLE
Easier access to common signals

### ISSUE THREAD

**Issue by mossblaser** [project-rig/rig#79]
Certain signals such as sync0 and app_stop particularly deserve easier access. The simplest option is to create trivial wrappers for them.

App-stop may deserve a "with" wrapper, perhaps one which also sets the app_id context...

**Comment by mundya** [comment]
> App-stop may deserve a "with" wrapper, perhaps one which also sets the app_id context...

Something like:
```python
with cn.app_stop_when_done(app_id=56):
    cn.do_something(...)
```

**Comment by mossblaser** [comment]
Excellent though I'd prefer `cn.application([number])` for neatness.

**Comment by mundya** [comment]
How about:

```python
with cn.application(app_id=66, targets={...}, routing_tables={...}):
    # Do whatever...
```

The `cn.application` loads applications and routing tables on enter (if provided) and frees them and app stops on exit?

**Comment by mossblaser** [comment]
Bit too heavy for my taste: I think just setting the App-ID context and setting up an appstop (and whatever cleanup ybug does) is sufficient. After all, we already have perfectly good APIs for loading apps/tables.
