### ISSUE TITLE
SCP

### ISSUE THREAD

**Issue by mundya** [project-rig/rig#8]
- [x] Load applications
- [ ] Signals
- [x] Boot
- [ ] Read/write struct values (from memory as a convenience)
- [x] Allocate memory
- [ ] Allocate routing table space
- [ ] Load routing tables

**Comment by mundya** [comment]
Some thoughts on using the `MachineController`, which is basically `ybug` in Python.

Most functions take `x`, `y`, `p` and `app_id` as arguments, it'd be nice to be able to work within a context where those don't need to be constantly passed in; so:

```python
cn = MachineController("hostname", app_id=30)  # The app_id is now set

with cn(x=1, y=1):  # Talking to chip (1, 1)
    cn.do_something(p=2)  # To processor (1, 1, 2)
    cn.do_something_else(x=3)  # To chip (3, 1, 2)

# Commands executed here NEED to have x and y specified because we didn't specify them before.

with cn(x=3, y=4):
    with cn(x=2, p=7, app_id=2):
        cn.do_something()  # To processor(2, 4, 7) with changed app_id
        cn.do_something(app_id=3)  # To processor (2, 4, 7) with app_id=2
```

Does this seem sane?

**Comment by mossblaser** [comment]
I'd have either withs *or* global context, just to KISS.

**Comment by mossblaser** [comment]
Feature implementation suggestion (and offer of implementation if required): The auto app-stop feature could be hooked into the context manager (also catches exceptions etc.):

    with cn(app_id=1, app_stop=True):
        ...
        with cp(...):
            ...
        ...

**Comment by mundya** [comment]
That's fine by me.  Is it worth subclassing the Mixin to provide this behaviour? On the pro side it leaves us with an unadulterated context thing, on the negative I don't think we need that...

**Comment by mossblaser** [comment]
A further alternative would be to allow the insertion of hooks into the CM Mixin, that way the MachineController itself can just hook the exit and check for the `app_stop` parameter. Subclassing is probably cleaner/preferable, though.

I'd prefer to keep the context thing unadulterated. If nothing else it is something that should really be a standard library thingy... (And may be one day...).

**Comment by mundya** [comment]
Closing this issue because the pull request duplicates most of the information.
