### ISSUE TITLE
Support SpiNNaker tools 1.4

### ISSUE THREAD

**Issue by mundya** [project-rig/rig#82]
- [ ] ~~New struct file format~~ Not changing anymore.
 - [x] Remove e223add

**Comment by mundya** [comment]
Do we want to make this a requirement for release 1.0.0, given that if we released 1.0.0 and then supported SpiNNaker tools 1.4 we'd probably have to bump the version number?

(I have little desire to support multiple versions of SpiNNaker tools...)

**Comment by mundya** [comment]
As suggested in #191, SCAMP 140 will have a "clear" flag in memory allocations:
 - [ ] Expose the clear flag when allocating memory

**Comment by mossblaser** [comment]
In #203 an implementation of `sark_tag_ptr` was included in the documentation to make up for its unfortunate exclusion in SC&MP 13x. This should be removed (and perhaps a historical note added) upon 140's release.

- [ ] Remove `sark_tag_ptr` implementation from the documentation.

**Comment by mundya** [comment]
I guess @mossblaser has gone one better with #235!
