### ISSUE TITLE
Get list of tags associated with BitField field

### ISSUE THREAD

**Issue by mundya** [project-rig/rig#85]
For testing purposes I'd like to be able to check which tags are associated with a field in a BitField.  @mossblaser, would this be an easy thing to do?

**Comment by mossblaser** [comment]
Should be, I think there is a dictionary inside the object... Are you
volunteering ;)?

**Comment by mundya** [comment]
Maybe, I'm guessing you'll be around tomorrow?  I don't know the BitField code as well as I'd like.

**Comment by mossblaser** [comment]
How'sat?

**Comment by mundya** [comment]
Sorry, I should have been clearer; I was hoping for:

```python
>>> x = BitField()
>>> x.add_field("spam", tags="tag1")
>>> x.add_field("eggs", tags=["tag1", "tag2"])
>>> x.get_assigned_tags()
{"spam": ["tag1"], "eggs": ["tag1", "tag2"]}
```

**Comment by mundya** [comment]
So that shouldn't be ridiculous, I'll try that.

**Comment by mundya** [comment]
Excellent, thank you :)
