### ISSUE TITLE
Data structure handling (a.k.a. 'Regions')

### ISSUE THREAD

**Issue by mossblaser** [project-rig/rig#99]
This issue aims to collect together thoughts on the problem currently solved by
the 'Regions' system and to either better understand it and hopefully improve
it.

# Requirements

**In a nutshell:** to assist in translating between Python data structures on
the host and C data structures spread across the SpiNNaker hardware.

* High-level
  * Translation must generally be bidirectional, though not all applications
    will require translating in both directions! Perhaps "read only", "write
    only" and "read/writable" could be the three possible classes... Perhaps
    not, though... (**Regions do not explicitly represent this information.** Is
    this a bug or a feature?)
  * Data structures on the (single) host may be spread across multiple SpiNNaker
    devices.
  * Data structures will be relocatable (i.e. no absolute pointers) and the API
    should not need to know the locations where generated blocks will be
    written.
* API
  * A common interface should be defined which all data types should obey.
  * Should very cleanly interface with appropriate MachineController methods
    *and* with file-likes (to allow easy dumping/caching) with minimal
    boilerplate code. Minimal magic should be involved! Note that this API
    should ideally allow data to be referred to with minimal unnecessary
    duplication.
  * It should be possible to divide certain data structures (e.g. matrices),
    ideally without duplicating memory.
  * Interface should allow lazy evaluation of structure contents. Note that it
    should be considered acceptable to have a whole SDRAM-worth of data in RAM
    at once.
  * Should provide ready-made implementations of common data structures, a
    complementary (and minimal) C library should be provided for interpreting
    these (to reduce ambiguity), but considered optional and formatting should
    be carefully described in documentation.
  * Should be possible to compose and nest certain data structures
  * Certain compound types should support "slicing" with minimal copying where
    possible.
* (Potential) Included data types
  * Primitives
    * Pointer
    * Char
    * Int/uint/etc.
    * Float/Double
    * Fixed-point
    * String/Bytes
  * Compound
    * (C-style) Struct
    * Array
    * Linked list(?)
    * Key-Value store (with fixed set of keys)
    * Dictionary(?)
  * Numpy
    * Int
    * Float
    * Double
    * Fixed point
    * Matrix
  * Functional
    * Map (e.g. for 'keyspaces')

# Naming

It has been noted that the name 'Region' has been too heavily overloaded and
perhaps doesn't get-across what this module is doing.

Since this functionality principally deals with the problem of data-structure
definition and translation. As a result, I propose the submodule is renamed
`data` and that the base data type is called `DataStructure`. I'd welcome better
suggestions!

An alternative briefly considered was something like 'serialisation' and
'deserialisation' however this (to me) has implications of an intermediate
'serialised' representation somewhere.

# Work flow

As best I understand, the Regions work flow looks something like this:

1. Create underlying python/numpy/etc object
1. Create corresponding regions
1. Do place-and-route
1. In a hard-coded loop, for each app, for non-read-only regions, write a
   subset of the region to memory
1. Run application
1. In a hard-coded loop, for each app, for non-write-only regions, read a
   subset of the region from memory.
1. Underlying objects are updated

It occurs to me that the following slight change would make things somewhat
cleaner:

1. Create underlying python/numpy/etc object
1. Create corresponding DataStructure objects, noting which are read-only and
   which are write-only and which are read/write.
1. For each app: create refinements of the above data structures (e.g.
   splitting off chunks of matrices)
1. Do place-and-route
1. For each app: load DataStructures, skipping ones marked read-only
1. Run application
1. For each app: read DataStructures, skipping ones marked write-only
1. Underlying objects are updated

This flow (I hope) provides the following benefits

* Move "partitioning" logic closer to the definition of data structures and
  the application graph.
* Applications which don't do any form of partitioning need not even think about
  such concepts.
* By specifying all partitioning details and read/write needs earlier on (where
  it is contextually more relevant), later machine-management code (the actual
  loading) can be really dumb: "just load these DataStructures to these
  locations".
* No duplication of logic for deciding what to load/read or not and to which
  partitions.

# More to follow...

Will shortly do some thinking about what the API could/should look like and
generate some idealised code examples.

I would very much welcome feedback from @mundya and @neworderofjamie on the
above requirements and work flows. I'm largely basing these on my understanding
of what you're both doing and from my own requirements hit while building the
network testing program I'm working on.

**Comment by neworderofjamie** [comment]
Some thoughts:
* I can't think of a good case for readwrite regions
* I don't honestly know if we ever write anything complex enough to justify very much work in this area on either side of the C/Python divide - My personal approach would be to generalise when and if we see any need
  * In python the majority of the time, the data is easily turned to bytes with numpy or struct
  * In C, as both numpy and struct handle padding for you, memcpy / casting is normally enough for the simple cases and the more weird cases are going to be very hard to generalise.

**Comment by mossblaser** [comment]
Re: read/write, me neither though I suspect any real implementation will make it more effort not to have them than have them. With regards to the second point, you may well be right.

The motivation for some of these is, for example, when you write out a matrix at may commonly be useful to include its dimensions (for example) and so a very thin layer which on one side has a matrix and on the other a file-like interface (or similar) is all thats needed. Basically all of these use cases are just paper-thin but potentially useful wrappers around numpy's packing functions and python's "struct" module. The advantage they offer is a consistent interface when it comes to actually reading/writing data to the machine.

An alternative solution to the problem is to remove the whole thing from Rig and leave everything up to the user. Scanning over pinus_rigida, as far as I can tell, the only feature of the existing Region's system you're using is essentially just the standard interface for a Region. As far as I can tell, they don't appear in Mundy's new nengo implementation (yet, at least).

@neworderofjamie do you foresee using any of the current "Region" features in rig? From what I can see from my quick glance, you seem to handle everything with minimal fuss already.

@mundya what are your thoughts on the proposal of removing the regions thing? The more I think about the problem, the more it seems like you'd need an all-encompassing (and as Jamie says, probably over sized) library while in reality, most users needs are simple enough that there isn't much benefit of making something "general purpose". The existing (and proposed) libraries are, after all, paper thin... Certainly, it seems like the more general useful things have already been split up (e.g. type_casts).

**Comment by mundya** [comment]
@mossblaser I've been considering proposing removing regions for a bit.  It made sense when PACMAN enforced a work-flow, but given that we actively aim to avoid doing that they don't seem appropriate here.

(Re: Nengo/SpiNNaker, regions _might_ get used, but I probably don't want to be forced to work a certain way by Rig)

**Comment by mossblaser** [comment]
>  I've been considering proposing removing regions for a bit.

This is comforting to hear.

> given that we actively aim to avoid [enforcing a particular workflow] they don't seem appropriate here.

That sounds about right. It seems at the moment that there are no obvious reasons to use Regions in many applications since it isn't mandatory in any way and they currently only offer limited functionality. As Jamie notes, adding more functionality to make them useful for more users (e.g. as described in this issue) may simply result in code bloat for little benefit to most users.

> Re: Nengo/SpiNNaker, regions might get used

Presumably migrating this code to Nengo SpiNNaker would be appropriate in this case? Similarly, in pinus_rigida, the base class (or similar) can simply be moved into the project.

@mundya, @neworderofjamie Could I get a show of hands for removing Regions from Rig at this point? Are there any sub features that you'd like to see preserved or would miss?

**Comment by mundya** [comment]
I'm happy for this to go.

**Comment by mossblaser** [comment]
@neworderofjamie has also agreed that this can be removed.

PR #101 removes Regions from Rig. Awaiting sanity check/review!
